### ISSUE TITLE
Peer-to-peer Code Review

### ISSUE THREAD

**Issue by okoyecharles** [Said-laasri/To-do-List#2]
Your project looks amazing although here are some suggestions on making your website amazing

## Changes Required  ♻
- [ ] On your `index.js` I suggest you use a forEach loop instead of the traditional for loop.

**Comment by AsimKhan2019** [comment]
Nicely done, the code is clean and the project is well structured, the way web pack suggested.

**Comment by Said-laasri** [comment]
@AsimKhan2019  @OkoyeCharles  thanks for your compliment and suggestions appreciated, 
will do better.
